### ISSUE TITLE
Starting debugserver without root?

### ISSUE THREAD

**Issue by wojciech-kulik** [lemon4ex/XcodeRootDebug#4]
Hi,

I'm looking for some information regardless starting debugserver. It seems like you have some knowledge about that. Do you know if it is possible to start debugserver without root on an iPhone?

I tried things like:
```
xcrun devicectl device process launch -d XYZ /Developer/usr/bin/debugserver
```

but with no luck. Any help would be appreciated

**Comment by lemon4ex** [comment]
What do you mean by root? Jailbroken devices can be debugbed using debugserver, as for whether they are root privileges can be adjusted as needed, non-jailbroken devices should only be debugged with the help of Xcode attach or startup process

**Comment by wojciech-kulik** [comment]
I meant non-jailbroken devices. Is it possible to start debugserver then?

**Comment by lemon4ex** [comment]
As far as I know, debugging is only possible with the help of Xcode

**Comment by lemon4ex** [comment]
> I meant non-jailbroken devices. Is it possible to start debugserver then?

As far as I know, debugging is only possible with the help of Xcode

**Comment by wojciech-kulik** [comment]
:( ok, thank you for your help! 👍
